import { Color } from "@/constants/Color";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1 },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: Color.spacing.md,
    height: 56,
    position: "relative",
  },
  backButton: {
    position: "absolute",
    left: Color.spacing.md,
    padding: Color.spacing.sm,
    zIndex: 10,
  },
  title: { fontSize: 22, fontWeight: "bold", textAlign: "center" },
  scrollContent: { padding: Color.spacing.md, paddingBottom: Color.spacing.xl },
  profileHeaderCard: {
    alignItems: "center",
    paddingVertical: Color.spacing.lg,
    paddingHorizontal: Color.spacing.md,
    borderRadius: Color.borderRadius.md * 2,
    marginBottom: Color.spacing.md,
    marginTop: Color.spacing.xs,
  },
  avatarBadge: {
    width: 76,
    height: 76,
    borderRadius: 38,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: Color.spacing.md,
  },
  avatarText: {
    color: "#ffffff",
    fontSize: 26,
    fontWeight: "bold",
    letterSpacing: 0.5,
  },
  userNameText: { fontSize: 22, fontWeight: "bold", textAlign: "center" },
  userEmailText: {
    fontSize: 14,
    fontWeight: "500",
    marginTop: 4,
    textAlign: "center",
  },
  blockLabel: {
    fontSize: 11,
    textTransform: "uppercase",
    fontWeight: "700",
    letterSpacing: 1.2,
    paddingLeft: 4,
    marginBottom: Color.spacing.sm,
    marginTop: Color.spacing.md,
  },
  metricsRow: {
    flexDirection: "row",
    paddingVertical: Color.spacing.lg,
    borderRadius: Color.borderRadius.md * 2,
    marginBottom: Color.spacing.md,
    justifyContent: "center",
  },
  metricColumn: { alignItems: "center", width: "100%" },
  metricCount: {
    fontSize: 20,
    fontWeight: "bold",
    marginTop: Color.spacing.xs,
  },
  metricLabel: { fontSize: 13, marginTop: 2, fontWeight: "500" },
  menuContainer: {
    borderRadius: Color.borderRadius.md * 2,
    paddingHorizontal: Color.spacing.md,
    marginBottom: Color.spacing.xl,
  },
  menuRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: Color.spacing.md,
    height: 56,
  },
  menuLeftSection: {
    flexDirection: "row",
    alignItems: "center",
    gap: Color.spacing.md,
  },
  menuTitleText: { fontSize: 15, fontWeight: "600" },
  menuDivider: { height: 1, width: "100%" },
  logoutButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Color.spacing.xs,
    borderWidth: 1.5,
    borderRadius: Color.borderRadius.md,
    paddingVertical: Color.spacing.md,
    width: "100%",
  },
  logoutButtonText: { fontSize: 16, fontWeight: "bold" },
});
